# Generated by Django 4.1.2 on 2024-06-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testfilepath_is_user_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfilepath',
            name='directory',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
    ]
